# Generated by Django 4.2.2 on 2023-06-20 17:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(default='1', primary_key=True, serialize=False)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=2550)),
                ('type', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=2550)),
                ('comments', models.BooleanField(default=True)),
                ('top_img', models.CharField(max_length=255)),
                ('cover', models.CharField(max_length=2550)),
                ('mathjax', models.CharField(max_length=255)),
                ('katex', models.CharField(max_length=255)),
                ('aside', models.CharField(max_length=2550)),
                ('aplayer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSort',
            fields=[
                ('id', models.IntegerField(default='1', primary_key=True, serialize=False)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('article_name', models.CharField(max_length=255)),
                ('article_alias', models.CharField(max_length=255)),
                ('article_description', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='FileControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='资源名称')),
                ('type', models.CharField(max_length=255, verbose_name='资源类型')),
                ('suffix_name', models.CharField(max_length=255, verbose_name='后缀名')),
                ('flie_path', models.CharField(max_length=255, verbose_name='资源路径')),
            ],
        ),
        migrations.CreateModel(
            name='Lables',
            fields=[
                ('id', models.IntegerField(default='1', primary_key=True, serialize=False)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('acticle_id', models.CharField(max_length=255, verbose_name='文章id')),
                ('label_id', models.CharField(max_length=255, verbose_name='标签id')),
            ],
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.IntegerField(default='1', primary_key=True, serialize=False)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('acticle_id', models.CharField(max_length=255, verbose_name='文章id')),
                ('sort_id', models.CharField(max_length=255, verbose_name='标签id')),
            ],
        ),
    ]
